version: "3.8"

services:
    web:
        build:
            context: .
            dockerfile: scripts/docker/Dockerfile
        image: oauth
        container_name: oauth_web
        volumes:
            - ./:/var/www
        ports:
            - "9000:9000"
        networks:
            - oauth
        depends_on:
            - mysql
            - nginx
            - redis
    mysql:
        image: mysql:5.7.33
        container_name: oauth_mysql
        restart: unless-stopped
        tty: true
        ports:
            - "3306:3306"
        environment:
            MYSQL_DATABASE: oauth
            MYSQL_ROOT_PASSWORD: 1
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - oauth
    nginx:
        image: nginx:stable-alpine
        container_name: oauth_nginx
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./scripts/docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            - oauth
    redis:
        image: redis:alpine
        container_name: oauth_redis
        ports:
            - "6379:6379"
        networks:
            - oauth
networks:
    oauth:
